# ... (início do arquivo)
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASK_LIST_A8D75 }}'
          channelId: live
          projectId: task-list-a8d75
          entryPoint: ./   # <--- GARANTA QUE ESTA LINHA ESTEJA AQUI
